#!/usr/bin/bash
# ClipsNeko Linux dotfiles installation script.

export DF_SRC=/usr/share/clipsneko-dotfiles
UNATTENDED=false
if [[ "$1" == "-y" ]]; then
    UNATTENDED=true
fi
echo "ClipsNeko Linux Hyprland dotfiles installation..."
if [[ "$UNATTENDED" != true ]]; then
    echo "This operation will override your current configs. Do you sure you want to continue?"
    read -p "Continue? (y/N) " -r confirm
    shopt -s nocasematch
    if [[ "$confirm" != "y" && "$confirm" != "yes" ]]; then
        echo "Cancelled."
        exit 1
    fi
    shopt -u nocasematch
fi

if [[ ! -d "$HOME/.config" ]]; then
    mkdir $HOME/.config
fi

rm -rf $HOME/.config/hypr
cp -r $DF_SRC/hypr $HOME/.config/
rm -rf $HOME/.config/mako
cp -r $DF_SRC/mako $HOME/.config/
rm -rf $HOME/.config/kitty
cp -r $DF_SRC/kitty $HOME/.config/
rm -rf $HOME/.config/waybar
cp -r $DF_SRC/waybar $HOME/.config/

echo "Done."
